---
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: bestuser
    password: bestuser
  jpa:
    hibernate:
      ddl-auto: update
